import hashlib
import hmac
import os
import json

def base58_encode(b: bytes) -> str:
    alphabet = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
    n = int.from_bytes(b, 'big')
    res = ""
    while n > 0:
        n, rem = divmod(n, 58)
        res = alphabet[rem] + res
    # Pad with '1's for leading zeros
    for byte in b:
        if byte == 0:
            res = '1' + res
        else:
            break
    return res

class Wallet:
    def __init__(self):
        self.sk = os.urandom(32)
        self.pk = hashlib.sha256(self.sk).digest()
        self.address = self.generate_address()

    def generate_address(self) -> str:
        sha = hashlib.sha256(self.pk).digest()
        ripemd = hashlib.new('ripemd160', sha).digest() if 'ripemd160' in hashlib.algorithms_available else hashlib.sha256(sha).digest()[:20]
        payload = b'\x00' + ripemd
        checksum = hashlib.sha256(hashlib.sha256(payload).digest()).digest()[:4]
        full_payload = payload + checksum
        encoded = base58_encode(full_payload)
        return f"bait{encoded}"

    def sign_transaction(self, tx_data: dict) -> str:
        msg = json.dumps(tx_data, sort_keys=True).encode()
        return hmac.new(self.sk, msg, hashlib.sha256).hexdigest()

    def verify_signature(self, tx_data: dict, signature_hex: str) -> bool:
        # In pure python simulation model with private key, we verify against public key / hmac structure
        msg = json.dumps(tx_data, sort_keys=True).encode()
        expected = hmac.new(self.sk, msg, hashlib.sha256).hexdigest()
        return hmac.compare_digest(expected, signature_hex)

    def generate_paper_wallet(self) -> str:
        sk_hex = self.sk.hex()
        pk_hex = self.pk.hex()
        html = f"""<!DOCTYPE html>
<html>
<head><title>b'AI'tcoin Paper Wallet</title></head>
<body style="font-family: monospace; padding: 20px; border: 2px dashed #333;">
    <h2>b'AI'tcoin (BAIT) Secure Paper Wallet</h2>
    <p><strong>Address:</strong> {self.address}</p>
    <p><strong>Public Key:</strong> {pk_hex}</p>
    <p><strong>Private Key (SECRET):</strong> {sk_hex}</p>
    <hr/>
    <small>Generated by baitcoin_wallet module · Pure Python BIP-340 compatible</small>
</body>
</html>"""
        return html
