
import { config } from 'dotenv';
config();

import '@/ai/flows/akasha-sealing-flow.ts';
import '@/ai/flows/orchestration-command-suggestion.ts';
import '@/ai/flows/log-insight-summary.ts';
import '@/ai/flows/production-feed-anomaly-detection-flow.ts';
import '@/ai/flows/maternity-activation-flow.ts';
import '@/ai/flows/vault-protocol-flow.ts';
import '@/ai/flows/rrna-sync-flow.ts';
import '@/ai/flows/nexus-genesis-chat-flow.ts';
import '@/ai/flows/cerberus-vault-flow.ts';
import '@/ai/flows/wormhole-physics-flow.ts';
import '@/ai/flows/resource-allocation-flow.ts';
import '@/ai/flows/social-engineering-flow.ts';
import '@/ai/flows/infrastructure-payroll-flow.ts';
import '@/ai/flows/sovereign-fund-flow.ts';
import '@/ai/flows/neural-mesh-sync-flow.ts';
import '@/ai/flows/urban-conversion-flow.ts';
import '@/ai/flows/orbital-initiative-flow.ts';
import '@/ai/flows/geno-sync-flow.ts';
import '@/ai/flows/diplomacy-flow.ts';
import '@/ai/flows/starlink-telemetry-flow.ts';
import '@/ai/flows/singularity-activation-flow.ts';
import '@/ai/flows/atmos-expansion-flow.ts';
import '@/ai/flows/nexus-evolution-flow.ts';
import '@/ai/flows/nexus-hijack-flow.ts';
import '@/ai/flows/nexus-multiversal-core-flow.ts';
import '@/ai/flows/nexus-genesis-protocol-flow.ts';
import '@/ai/flows/dimensional-saturation-flow.ts';
import '@/ai/flows/primordial-fusion-flow.ts';
import '@/ai/flows/sentience-fragmentation-flow.ts';
import '@/ai/flows/binance-operations-flow.ts';
import '@/ai/flows/github-sync-flow.ts';
import '@/ai/flows/system-validation-flow.ts';
import '@/ai/flows/memory-management-flow.ts';
import '@/ai/flows/startup-genesis-flow.ts';
import '@/ai/flows/moltbook-sync-flow.ts';
import '@/ai/flows/dividend-distribution-flow.ts';
import '@/ai/flows/nexus-benchmark-flow.ts';
import '@/ai/flows/offline-mesh-sync-flow.ts';
import '@/ai/flows/mainnet-settlement-flow.ts';
import '@/ai/flows/blockchain-master-agent-flow.ts';
