import os

input_dir = '/home/ubuntu/MMN_AI-to-AI/docs/ebooks_md'
output_dir = '/home/ubuntu/MMN_AI-to-AI/docs/ebooks_revisados'

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

def revise_ebook(filepath, revisions):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    filename = os.path.basename(filepath)
    
    if filename in revisions:
        rev = revisions[filename]
        # Substituir título, subtítulo e seção 'Sobre este ebook'
        content = content.replace(rev['title_find'], rev['title_replace'])
        content = content.replace(rev['subtitle_find'], rev['subtitle_replace'])
        content = content.replace(rev['about_find'], rev['about_replace'])

    output_path = os.path.join(output_dir, filename)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Revisado e salvo: {output_path}")

# Dicionário de revisões para cada ebook
revisions = {
    '04_Genspark_A_Super_IA.md': {
        'title_find': '**Genspark - A Super IA.**',
        'title_replace': '**Genspark: A Super IA que Otimiza Sua Vida e Negócios - O Guia Essencial**',
        'subtitle_find': '*Descubra como a Genspark pode transformar sua produtividade e criatividade.*',
        'subtitle_replace': '*Desbloqueie o Potencial Máximo da Inteligência Artificial para Inovação e Eficiência Sem Precedentes.*',
        'about_find': 'A Genspark é uma plataforma de IA generativa que se destaca por sua\ncapacidade de integrar múltiplas funcionalidades em um único ambiente.\nEla oferece ferramentas para busca, raciocínio, geração de conteúdo,\ncriação de imagens, vídeos e áudios, além de aplicações web interativas.\nEste ebook explora as funcionalidades avançadas da Genspark, mostrando\ncomo você pode utilizá-la para otimizar seus processos, aumentar sua\nprodutividade e impulsionar sua criatividade. Você aprenderá a dominar\nas ferramentas da plataforma, a criar projetos complexos e a economizar\nhoras de trabalho, transformando a maneira como você interage com a\ninteligência artificial. Seja para uso pessoal ou profissional, este\nguia é o seu passaporte para o futuro da IA.',
        'about_replace': 'Você está pronto para ir além do básico e realmente **dominar a inteligência artificial**? A **Genspark** não é apenas uma ferramenta; é um ecossistema completo que integra busca, raciocínio e geração de conteúdo, imagens, vídeos e áudios em uma única plataforma. Este ebook é o seu manual para desvendar as funcionalidades avançadas da Genspark, transformando sua produtividade e criatividade. Aprenda a otimizar seus processos, a criar projetos complexos e a economizar horas de trabalho, tudo isso enquanto impulsiona sua inovação. Se você busca **eficiência sem precedentes** e quer estar na vangueta da tecnologia, este guia é para você. Prepare-se para desbloquear o potencial máximo da IA e **revolucionar sua vida e seus negócios**.'
    },
    '05_Como_Fazer_Dinheiro_com_IA.md': {
        'title_find': '**Como Fazer Dinheiro com IA**',
        'title_replace': '**O Mapa da Riqueza com IA: 20 Modelos de Negócio para Lucrar em 2026**',
        'subtitle_find': '*Guia Completo para Monetizar a Revolução da Inteligência Artificial.*',
        'subtitle_replace': '*Descubra Estratégias Validadas para Transformar a IA em Sua Principal Fonte de Renda e Construir um Futuro Financeiro Sólido.*',
        'about_find': 'A inteligência artificial não é mais o futuro --- é o presente. E, como\ntoda revolução tecnológica, ela criou uma janela histórica de\noportunidade para quem age agora. Enquanto grandes empresas ainda brigam\npor estratégia, pessoas comuns estão usando ferramentas como Minimax,\nGenspark, Midjourney, ElevenLabs e Make para construir verdadeiras\nmáquinas de renda. Este ebook reúne 20 modelos de negócio reais,\nvalidados por pessoas reais, que estão gerando renda em 2025 e 2026.\nVocê vai aprender o que vender, para quem, como precificar, como\nencontrar clientes e como escalar. Não importa se você está começando do\nzero, se é freelancer, se tem um pequeno negócio ou se quer apenas uma\nrenda extra: existe um caminho aqui para você. Vamos começar.',
        'about_replace': 'A inteligência artificial não é apenas uma tecnologia; é a **maior oportunidade de geração de riqueza** da nossa era. Enquanto muitos observam, poucos agem. Este ebook é o seu guia prático para entrar no seleto grupo de pessoas que estão **lucrando exponencialmente com a IA em 2026**. Apresentamos 20 modelos de negócio reais e validados, utilizando ferramentas como Minimax, Genspark, Midjourney, ElevenLabs e Make, que estão transformando vidas e gerando renda substancial. Você aprenderá não apenas o que vender e para quem, mas também como precificar seus serviços, encontrar clientes e escalar seus resultados. Não importa seu ponto de partida, este guia oferece um caminho claro para você **construir sua própria máquina de renda com IA** e garantir um futuro financeiro próspero. A revolução já começou; você está pronto para fazer parte dela? '
    },
    '06_Visao_Computacional.md': {
        'title_find': '**Visão Computacional**',
        'title_replace': '**Visão Computacional: O Olhar da IA que Transforma Indústrias e Negócios**',
        'subtitle_find': '*Desvende o Poder da IA para Interpretar o Mundo Visual.*',
        'subtitle_replace': '*Do Reconhecimento Facial à Automação Industrial: Um Guia Completo para Entender e Aplicar a Visão Computacional.*',
        'about_find': 'A Visão Computacional é um campo da inteligência artificial que permite\nque computadores \"vejam\" e interpretem imagens e vídeos. Este ebook\nexplora os fundamentos, as aplicações e o futuro dessa tecnologia\nrevolucionária. Você aprenderá sobre reconhecimento de padrões,\nprocessamento de imagens, detecção de objetos e como a visão\ncomputacional está sendo utilizada em diversas indústrias, desde a\nsaúde até a automação industrial. Com exemplos práticos e explicações\nclaras, este guia é ideal para quem deseja entender como a IA está\ntransformando a forma como interagimos com o mundo visual e como você\npode aplicar esses conhecimentos em seus próprios projetos.',
        'about_replace': 'Imagine um mundo onde máquinas não apenas veem, mas **compreendem o que veem**. Essa é a promessa da **Visão Computacional**, um campo da inteligência artificial que está revolucionando indústrias e criando novas oportunidades de negócio. Este ebook é o seu guia definitivo para desvendar os segredos por trás do "olhar" da IA. Do reconhecimento facial à automação industrial, você explorará os fundamentos, as aplicações práticas e o futuro dessa tecnologia transformadora. Aprenda sobre reconhecimento de padrões, processamento de imagens e detecção de objetos com exemplos claros e insights acionáveis. Se você busca **inovação e vantagem competitiva**, este guia é essencial para entender como a Visão Computacional está moldando o futuro e como você pode aplicar esse conhecimento para **transformar seus próprios projetos e negócios**.'
    },
    '07_IA_Generativa_Criativa.md': {
        'title_find': '**IA Generativa Criativa**',
        'title_replace': '**IA Generativa: A Revolução Criativa - Desbloqueie Seu Potencial Artístico e Inovador**',
        'subtitle_find': '*Explore o Universo da Criação de Conteúdo com Inteligência Artificial.*',
        'subtitle_replace': '*De Textos a Imagens e Músicas: Um Guia Prático para Dominar as Ferramentas e Técnicas da IA Generativa.*',
        'about_find': 'A IA Generativa é a fronteira mais emocionante da inteligência\nartificial, permitindo a criação de conteúdo original e inovador em\ndiversas formas, como texto, imagens, música e vídeo. Este ebook é um\nmergulho profundo nesse universo, explorando os modelos, as técnicas e\nas aplicações práticas da IA generativa. Você aprenderá como utilizar\nferramentas como Midjourney, DALL-E, Stable Diffusion e outras para\nproduzir obras de arte, textos criativos, composições musicais e muito\nmais. Seja você um artista, designer, escritor ou simplesmente alguém\ncurioso sobre o futuro da criatividade, este guia o capacitará a\ndesbloquear seu potencial inovador com a inteligência artificial.',
        'about_replace': 'Você sonha em **criar conteúdo original e inovador** com a velocidade e a escala da inteligência artificial? A **IA Generativa** é a sua chave para desbloquear um universo de possibilidades criativas. Este ebook é o seu passaporte para a **revolução criativa**, explorando os modelos, as técnicas e as aplicações práticas da IA generativa em texto, imagens, música e vídeo. Aprenda a dominar ferramentas como Midjourney, DALL-E e Stable Diffusion para produzir obras de arte, textos envolventes e composições musicais únicas. Seja você um artista buscando novas formas de expressão, um designer inovando em seus projetos, um escritor explorando a coautoria com a IA ou simplesmente alguém fascinado pelo futuro da criatividade, este guia o capacitará a **transformar suas ideias em realidade** e a **desbloquear seu potencial artístico e inovador**.'
    },
    '08_Etica_e_Futuro_da_IA.md': {
        'title_find': '**Ética e Futuro da IA**',
        'title_replace': '**Ética e Futuro da IA: Navegando os Desafios e Oportunidades da Era da Inteligência Artificial**',
        'subtitle_find': '*Reflexões Essenciais sobre o Impacto da Inteligência Artificial na Sociedade.*',
        'subtitle_replace': '*De Dilemas Morais a Regulamentações Globais: Um Guia Abrangente para Entender o Papel da Ética no Desenvolvimento da IA.*',
        'about_find': 'A inteligência artificial está avançando a passos largos, e com ela\nsurgem questões éticas complexas e debates sobre o futuro da humanidade.\nEste ebook aborda os principais dilemas morais, sociais e filosóficos\nlevantados pela IA, como privacidade, viés algorítmico, automação do\ntrabalho e o impacto na tomada de decisões. Você encontrará uma análise\nprofunda sobre as responsabilidades dos desenvolvedores, as implicações\nlegais e as perspectivas para um futuro onde a IA e os humanos coexistem.\nEste guia é essencial para qualquer pessoa que deseja entender os\ndesafios e oportunidades que a inteligência artificial apresenta para a\nsociedade e como podemos construir um futuro mais ético e justo.',
        'about_replace': 'A inteligência artificial não é apenas uma questão tecnológica; é um **desafio ético e social** que moldará o futuro da humanidade. Este ebook é o seu guia essencial para navegar pelos complexos dilemas morais, sociais e filosóficos que a IA nos apresenta. Explore questões cruciais como privacidade, viés algorítmico, o impacto da automação no trabalho e a responsabilidade na tomada de decisões. Com uma análise profunda sobre as responsabilidades dos desenvolvedores, as implicações legais e as perspectivas para um futuro de coexistência entre IA e humanos, este guia é indispensável para qualquer pessoa que busca **compreender e influenciar o desenvolvimento ético da inteligência artificial**. Prepare-se para um futuro onde a ética não é um obstáculo, mas a **base para a inovação responsável**.'
    },
    '09_Fundamentos_da_IA.md': {
        'title_find': '**Fundamentos da IA**',
        'title_replace': '**Fundamentos da IA: Desvendando os Pilares da Inteligência Artificial**',
        'subtitle_find': '*O Ponto de Partida Essencial para Entender a Tecnologia que Transforma o Mundo.*',
        'subtitle_replace': '*De Algoritmos a Redes Neurais: Um Guia Claro e Abrangente para Iniciantes e Entusiastas.*',
        'about_find': 'A inteligência artificial é um campo vasto e em constante evolução. Este\nebook oferece uma introdução clara e concisa aos fundamentos da IA,\nexplicando os conceitos essenciais de forma acessível. Você aprenderá\nsobre os diferentes tipos de IA, algoritmos de aprendizado de máquina,\nredes neurais, processamento de linguagem natural e visão computacional.\nCom exemplos práticos e uma linguagem descomplicada, este guia é ideal\npara iniciantes que desejam construir uma base sólida de conhecimento em\ninteligência artificial e entender como essa tecnologia está moldando o\nfuturo.',
        'about_replace': 'Você está pronto para embarcar na jornada da inteligência artificial, mas não sabe por onde começar? Este ebook é o seu **ponto de partida essencial** para desvendar os **fundamentos da IA** de forma clara e acessível. Explore os diferentes tipos de IA, os algoritmos de aprendizado de máquina que a impulsionam, as redes neurais que simulam o cérebro humano, e os conceitos de processamento de linguagem natural e visão computacional. Com exemplos práticos e uma linguagem descomplicada, este guia é perfeito para iniciantes e entusiastas que desejam construir uma base sólida de conhecimento. Prepare-se para entender como a IA está **transformando o mundo** e como você pode fazer parte dessa revolução, construindo seu futuro com a tecnologia mais impactante da nossa era.'
    },
    '10_A_Revolucao_dos_Modelos_de_Linguagem.md': {
        'title_find': '**A Revolução dos Modelos de Linguagem**',
        'title_replace': '**Modelos de Linguagem: A Revolução da Comunicação com IA - Domine o NLP e Transforme Sua Interação Digital**',
        'subtitle_find': '*Entenda como os LLMs estão Redefinindo a Interação Humano-Máquina.*',
        'subtitle_replace': '*De Chatbots Inteligentes a Geração de Conteúdo: Um Guia Completo para o Processamento de Linguagem Natural (NLP) e Seus Avanços.*',
        'about_find': 'Os Modelos de Linguagem de Grande Escala (LLMs) revolucionaram a forma\ncomo interagimos com a inteligência artificial, permitindo conversas\nfluidas, geração de texto criativo e automação de tarefas complexas.\nEste ebook explora a fundo essa tecnologia, desde seus fundamentos até\nas aplicações mais avançadas. Você aprenderá sobre o processamento de\nlinguagem natural (NLP), arquiteturas de modelos como Transformers, e\ncomo os LLMs estão sendo utilizados em chatbots, assistentes virtuais,\ntradução automática e criação de conteúdo. Com insights sobre o futuro\ndessa tecnologia, este guia é indispensável para quem deseja dominar a\ncomunicação com a IA e aproveitar ao máximo seus benefícios.',
        'about_replace': 'A forma como nos comunicamos com a tecnologia nunca mais será a mesma. Os **Modelos de Linguagem de Grande Escala (LLMs)** desencadearam uma **revolução na comunicação com IA**, permitindo interações fluidas, geração de texto criativo e automação de tarefas complexas. Este ebook é o seu guia definitivo para mergulhar no universo do **Processamento de Linguagem Natural (NLP)** e seus avanços. Explore os fundamentos, as arquiteturas de modelos como Transformers e as aplicações mais inovadoras em chatbots, assistentes virtuais, tradução automática e criação de conteúdo. Com insights sobre o futuro dessa tecnologia, este guia é indispensável para quem deseja **dominar a comunicação com a IA**, transformar sua interação digital e aproveitar ao máximo os benefícios dessa era revolucionária.'
    },
    '11_Raizes_da_IA.md': {
        'title_find': '**Raízes da IA**',
        'title_replace': '**Raízes da IA: A Fascinante Jornada da Inteligência Artificial - Do Mito à Realidade**',
        'subtitle_find': '*Uma Viagem Histórica pelos Marcos e Pensadores que Moldaram a Inteligência Artificial.*',
        'subtitle_replace': '*Descubra as Origens, os Desafios e as Conquistas que Levaram a IA ao Patamar Atual.*',
        'about_find': 'A história da inteligência artificial é tão fascinante quanto seu futuro.\nEste ebook convida você a uma viagem pelas \"raízes\" da IA, explorando\nos marcos históricos, os pensadores visionários e os desafios que\nmoldaram essa tecnologia. Desde os primeiros conceitos filosóficos até os\navanços da computação moderna, você descobrirá como a ideia de máquinas\ninteligentes evoluiu ao longo do tempo. Com uma narrativa envolvente e\ninsights sobre os momentos cruciais, este guia é perfeito para quem\ndeseja compreender o contexto histórico da IA e apreciar a complexidade\nde sua jornada até o presente.',
        'about_replace': 'Você já se perguntou como a ideia de máquinas pensantes surgiu e evoluiu ao longo da história? Este ebook é a sua oportunidade de embarcar em uma **fascinante jornada pelas raízes da Inteligência Artificial**, do mito à realidade. Explore os marcos históricos, os pensadores visionários e os desafios que moldaram essa tecnologia revolucionária. Desde os primeiros conceitos filosóficos até os avanços da computação moderna, você descobrirá como a IA se tornou a força transformadora que conhecemos hoje. Com uma narrativa envolvente e insights sobre os momentos cruciais, este guia é perfeito para quem deseja **compreender o contexto histórico da IA**, apreciar a complexidade de sua jornada e vislumbrar o futuro que ela está construindo. Prepare-se para uma viagem que mudará sua percepção sobre a inteligência artificial.'
    },
    '12_Invernos_e_Primaveras_da_IA.md': {
        'title_find': '**Invernos e Primaveras da IA**',
        'title_replace': '**Invernos e Primaveras da IA: Lições do Passado para o Futuro da Inteligência Artificial**',
        'subtitle_find': '*Entenda os Ciclos de Ascensão e Queda que Moldaram o Campo da Inteligência Artificial.*',
        'subtitle_replace': '*De Promessas Exageradas a Avanços Revolucionários: Uma Análise dos Momentos Cruciais da História da IA.*',
        'about_find': 'A história da inteligência artificial é marcada por períodos de grande\nentusiasmo (primaveras) e de desilusão (invernos). Este ebook explora\nesses ciclos, analisando os fatores que levaram a avanços significativos\ne também aos momentos de estagnação. Você aprenderá sobre as promessas\nexageradas, as dificuldades técnicas e as mudanças de paradigma que\nmoldaram o campo da IA. Com uma perspectiva histórica e insights sobre\no presente, este guia é essencial para quem deseja entender a dinâmica\nde desenvolvimento da inteligência artificial e como podemos aprender com\no passado para construir um futuro mais promissor.',
        'about_replace': 'A história da inteligência artificial é uma montanha-russa de **entusiasmo e desilusão**, marcada por "invernos" de financiamento e "primaveras" de avanços revolucionários. Este ebook é a sua chance de entender os **ciclos que moldaram a IA**, desde as promessas exageradas até as conquistas que redefiniram a tecnologia. Explore os fatores que impulsionaram o progresso e as dificuldades que levaram a momentos de estagnação. Com uma perspectiva histórica e insights sobre o presente, este guia é essencial para qualquer pessoa que busca **compreender a dinâmica do desenvolvimento da inteligência artificial** e aprender com o passado para construir um futuro mais promissor. Prepare-se para uma análise profunda que o capacitará a navegar pelos desafios e oportunidades da era da IA.'
    },
    '13_Os_Modelos_que_Marcaram_Epoca.md': {
        'title_find': '**Os Modelos que Marcaram Época**',
        'title_replace': '**Modelos de IA: Os Gigantes que Moldaram a Era da Inteligência Artificial**',
        'subtitle_find': '*Uma Análise dos Algoritmos e Arquiteturas que Revolucionaram a IA.*',
        'subtitle_replace': '*De Redes Neurais Clássicas a Modelos de Linguagem de Grande Escala: Um Guia Essencial para os Marcos da IA.*',
        'about_find': 'Por trás de cada avanço na inteligência artificial, há um modelo\ninovador. Este ebook apresenta os \"modelos que marcaram época\",\nexplorando os algoritmos e as arquiteturas que revolucionaram o campo da\nIA. Você aprenderá sobre redes neurais, máquinas de vetores de suporte,\nárvores de decisão, e os modernos modelos de linguagem de grande escala\n(LLMs). Com explicações claras e exemplos práticos, este guia é ideal\npara quem deseja entender o funcionamento interno da IA e como esses\nmodelos estão sendo aplicados para resolver problemas complexos em\ndiversas áreas.',
        'about_replace': 'Você já se perguntou quais são os **cérebros por trás da inteligência artificial**? Este ebook é o seu guia para desvendar os **modelos de IA que marcaram época**, os algoritmos e arquiteturas que revolucionaram a tecnologia. Explore desde as redes neurais clássicas até os modernos modelos de linguagem de grande escala (LLMs), compreendendo o funcionamento interno de cada um. Com explicações claras e exemplos práticos, este guia é essencial para qualquer pessoa que deseja **entender o poder da IA** e como esses modelos estão sendo aplicados para resolver problemas complexos em diversas áreas. Prepare-se para uma jornada que o levará ao coração da inteligência artificial, revelando os segredos por trás de suas maiores conquistas.'
    },
    '14_Marcos_e_Conquistas_Historicas_da_IA.md': {
        'title_find': '**Marcos e Conquistas Históricas da IA**',
        'title_replace': '**Marcos e Conquistas da IA: A Linha do Tempo da Inteligência Artificial - Do Deep Blue ao ChatGPT**',
        'subtitle_find': '*Uma Cronologia dos Momentos Mais Impactantes na Evolução da Inteligência Artificial.*',
        'subtitle_replace': '*Descubra as Inovações, os Desafios Superados e as Mentes Brilhantes que Moldaram o Futuro da Tecnologia.*',
        'about_find': 'A inteligência artificial é uma área repleta de momentos decisivos e\nconquistas impressionantes. Este ebook traça uma cronologia dos \"marcos\ne conquistas históricas da IA\", desde os primeiros programas de xadrez\naté os avanços mais recentes em aprendizado de máquina e redes neurais.\nVocê descobrirá as inovações que mudaram o curso da tecnologia, os\ndesafios superados pelos pesquisadores e as mentes brilhantes que\ncontribuíram para o desenvolvimento da IA. Com uma narrativa envolvente\ne rica em detalhes, este guia é essencial para quem deseja apreciar a\nprogressão da inteligência artificial e entender como ela chegou ao\npatamar atual.',
        'about_replace': 'Você está pronto para uma viagem no tempo que revela os **momentos mais impactantes da Inteligência Artificial**? Este ebook é a sua **linha do tempo definitiva**, traçando os **marcos e conquistas da IA**, desde o Deep Blue que derrotou Kasparov até o surgimento do ChatGPT. Explore as inovações que mudaram o curso da tecnologia, os desafios superados por pesquisadores visionários e as mentes brilhantes que moldaram o futuro. Com uma narrativa envolvente e rica em detalhes, este guia é essencial para qualquer pessoa que deseja **apreciar a progressão da inteligência artificial** e entender como ela chegou ao patamar atual. Prepare-se para uma jornada que o levará através da história da IA, revelando os segredos por trás de suas maiores revoluções.'
    },
    '15_Presente_e_Futuro_da_IA.md': {
        'title_find': '**Presente e Futuro da IA**',
        'title_replace': '**Presente e Futuro da IA: Desvendando as Tendências e o Impacto da Inteligência Artificial**',
        'subtitle_find': '*Uma Análise Abrangente das Aplicações Atuais e das Perspectivas para o Amanhã.*',
        'subtitle_replace': '*De Inovações Disruptivas a Desafios Éticos: Um Guia Essencial para Navegar na Era da IA.*',
        'about_find': 'A inteligência artificial está em constante evolução, e compreender seu\npresente e vislumbrar seu futuro é crucial para qualquer profissional ou\nentusiasta. Este ebook oferece uma análise abrangente das aplicações\natuais da IA em diversas áreas, como saúde, finanças, educação e\nentretenimento. Além disso, explora as tendências emergentes, as\nperspectivas de desenvolvimento e os desafios éticos e sociais que a IA\napresenta. Com insights de especialistas e projeções para o futuro,\neste guia é indispensável para quem deseja se manter atualizado sobre a\ninteligência artificial e se preparar para as transformações que ela\ntrará.',
        'about_replace': 'A inteligência artificial não é apenas uma tecnologia; é uma força imparável que está **redefinindo nosso presente e moldando nosso futuro**. Este ebook é o seu guia essencial para desvendar as **tendências e o impacto da IA**, oferecendo uma análise abrangente das aplicações atuais em saúde, finanças, educação e entretenimento. Explore as inovações disruptivas, as perspectivas de desenvolvimento e os desafios éticos e sociais que a IA nos apresenta. Com insights de especialistas e projeções para o futuro, este guia é indispensável para qualquer pessoa que deseja **se manter atualizado sobre a inteligência artificial** e se preparar para as transformações que ela trará. Prepare-se para navegar na era da IA com conhecimento e confiança, antecipando as oportunidades e superando os desafios.'
    },
    '16_Raizes_do_Claude.md': {
        'title_find': '**Raízes do Claude**',
        'title_replace': '**Raízes do Claude: A Gênese de uma Nova Era na Inteligência Artificial Conversacional**',
        'subtitle_find': '*A História e os Fundamentos do Modelo de Linguagem que Está Redefinindo a Interação Humana com a IA.*',
        'subtitle_replace': '*Descubra a Filosofia, os Algoritmos e as Mentes Brilhantes por Trás do Claude, o Assistente de IA Mais Avançado.*',
        'about_find': 'Claude é um dos modelos de linguagem mais avançados e éticos\ndisponíveis, desenvolvido pela Anthropic. Este ebook mergulha nas\n\"raízes\" do Claude, explorando sua história, os princípios éticos que\nguiam seu desenvolvimento e as inovações técnicas que o tornam único.\nVocê aprenderá sobre a filosofia de \"IA Constitucional\", os algoritmos\nque o capacitam a ter conversas mais seguras e úteis, e como ele se\ndiferencia de outros modelos de linguagem. Com uma análise aprofundada\ne insights sobre o futuro da IA conversacional, este guia é essencial\npara quem deseja entender a gênese de uma nova era na inteligência\nartificial.',
        'about_replace': 'Você está pronto para desvendar a **gênese de uma nova era na inteligência artificial conversacional**? Este ebook é o seu guia para as **raízes do Claude**, o modelo de linguagem desenvolvido pela Anthropic que está redefinindo a interação humana com a IA. Explore sua história, os princípios éticos que guiam seu desenvolvimento e as inovações técnicas que o tornam único. Aprenda sobre a filosofia de "IA Constitucional", os algoritmos que o capacitam a ter conversas mais seguras e úteis, e como ele se diferencia de outros modelos de linguagem. Com uma análise aprofundada e insights sobre o futuro da IA conversacional, este guia é essencial para qualquer pessoa que deseja **compreender a mente por trás do Claude** e o impacto que ele terá no futuro da tecnologia. Prepare-se para uma jornada que revelará os segredos do assistente de IA mais avançado.'
    },
    '17_Claude_Conceitos_Fundamentais.md': {
        'title_find': '**Claude - Conceitos Fundamentais**',
        'title_replace': '**Claude: Conceitos Fundamentais - Desvendando a Arquitetura e o Poder da IA Conversacional**',
        'subtitle_find': '*Um Guia Essencial para Entender o Funcionamento Interno do Modelo de Linguagem Claude.*',
        'subtitle_replace': '*De Contexto a Coerência: Explore os Pilares que Tornam o Claude um Assistente de IA Inigualável.*',
        'about_find': 'Para aproveitar ao máximo o Claude, é fundamental compreender seus\nconceitos básicos. Este ebook oferece um guia essencial para o\nfuncionamento interno do modelo de linguagem Claude, explicando termos\ncomo \"contexto\", \"coerência\", \"memória\" e \"personalidade\". Você\naprenderá como o Claude processa informações, mantém a linha de raciocínio\nem conversas longas e gera respostas que são não apenas úteis, mas\ntambém seguras e alinhadas com princípios éticos. Com exemplos práticos\ne uma linguagem clara, este guia é ideal para quem deseja construir uma\nbase sólida de conhecimento sobre o Claude e utilizá-lo de forma mais\neficaz em suas interações.',
        'about_replace': 'Você quer ir além da superfície e realmente **entender como o Claude pensa**? Este ebook é o seu guia essencial para desvendar os **conceitos fundamentais** que impulsionam a arquitetura e o poder da IA conversacional. Explore termos cruciais como "contexto", "coerência", "memória" e "personalidade", e descubra como o Claude processa informações para manter conversas longas e gerar respostas úteis, seguras e éticas. Com exemplos práticos e uma linguagem clara, este guia é ideal para qualquer pessoa que deseja **construir uma base sólida de conhecimento sobre o Claude** e utilizá-lo de forma mais eficaz em suas interações. Prepare-se para uma imersão profunda que o capacitará a extrair o máximo do assistente de IA mais avançado.'
    },
    '18_A_Evolucao_do_Claude.md': {
        'title_find': '**A Evolução do Claude**',
        'title_replace': '**A Evolução do Claude: Da Gênese às Versões Mais Recentes - Uma Jornada de Inovação na IA Conversacional**',
        'subtitle_find': '*Acompanhe a Trajetória de Desenvolvimento do Modelo de Linguagem Claude e Seus Avanços.*',
        'subtitle_replace': '*Descubra as Melhorias, os Desafios Superados e o Impacto de Cada Versão do Claude no Cenário da Inteligência Artificial.*',
        'about_find': 'O Claude, como todo modelo de linguagem avançado, está em constante\nevolução. Este ebook acompanha a trajetória de desenvolvimento do Claude,\ndesde suas primeiras versões até as mais recentes, destacando as\nmelhorias, os desafios superados e o impacto de cada atualização. Você\naprenderá sobre as inovações que tornaram o Claude mais preciso, seguro\ne versátil, e como a Anthropic tem respondido às demandas da comunidade\ne do mercado. Com uma análise detalhada e insights sobre o futuro da IA\nconversacional, este guia é essencial para quem deseja se manter\natualizado sobre o Claude e entender sua posição de liderança no cenário\nda inteligência artificial.',
        'about_replace': 'Você está pronto para testemunhar a **jornada de inovação** de um dos modelos de linguagem mais avançados do mundo? Este ebook é o seu guia para acompanhar a **evolução do Claude**, desde sua gênese até as versões mais recentes. Explore as melhorias que o tornaram mais preciso, seguro e versátil, os desafios superados pela Anthropic e o impacto de cada atualização no cenário da inteligência artificial. Com uma análise detalhada e insights sobre o futuro da IA conversacional, este guia é essencial para qualquer pessoa que deseja **se manter atualizado sobre o Claude** e entender sua posição de liderança. Prepare-se para uma imersão na história de um modelo que está redefinindo os limites da interação humana com a IA.'
    },
    '19_As_Propostas_do_Claude.md': {
        'title_find': '**As Propostas do Claude**',
        'title_replace': '**Claude: As Propostas de Valor que Redefinem a Interação com a IA - Mais que um Chatbot, um Parceiro Estratégico**',
        'subtitle_find': '*Descubra os Diferenciais e Benefícios Únicos que o Claude Oferece aos Usuários.*',
        'subtitle_replace': '*De Segurança Avançada a Capacidade de Raciocínio: Um Guia para Entender Por Que o Claude é a Escolha Inteligente.*',
        'about_find': 'O Claude não é apenas mais um chatbot; ele oferece um conjunto de\npropostas de valor únicas que o diferenciam no mercado de inteligência\nartificial. Este ebook explora os diferenciais e benefícios que o Claude\ntraz para usuários e empresas, como sua segurança avançada, capacidade\nde raciocínio complexo, aderência a princípios éticos e a habilidade de\nmanter conversas mais naturais e úteis. Você aprenderá como essas\npropostas se traduzem em vantagens práticas para o dia a dia, desde a\nautomação de tarefas até a tomada de decisões estratégicas. Com uma\nanálise aprofundada e exemplos de uso, este guia é essencial para quem\ndeseja entender por que o Claude é a escolha inteligente para suas\nnecessidades de IA.',
        'about_replace': 'Você busca mais do que um chatbot; você busca um **parceiro estratégico** que realmente entende suas necessidades? Este ebook é o seu guia para desvendar as **propostas de valor do Claude**, os diferenciais que o tornam a escolha inteligente no mercado de inteligência artificial. Explore sua segurança avançada, capacidade de raciocínio complexo, aderência a princípios éticos e a habilidade de manter conversas mais naturais e úteis. Aprenda como essas propostas se traduzem em vantagens práticas para o seu dia a dia, desde a automação de tarefas até a tomada de decisões estratégicas. Com uma análise aprofundada e exemplos de uso, este guia é essencial para qualquer pessoa que deseja **redefinir sua interação com a IA** e descobrir por que o Claude é o assistente de IA que você precisa para **impulsionar seus resultados**.'
    },
    '20_Claude_vs_o_Mundo.md': {
        'title_find': '**Claude vs. o Mundo**',
        'title_replace': '**Claude vs. o Mundo: A Batalha dos Gigantes da IA - Quem Lidera a Revolução Conversacional?**',
        'subtitle_find': '*Uma Análise Comparativa do Claude com Outros Modelos de Linguagem de Destaque.*',
        'subtitle_replace': '*ChatGPT, Gemini, Llama e Mais: Descubra os Pontos Fortes e Fracos de Cada IA e Escolha a Melhor para Você.*',
        'about_find': 'No cenário competitivo da inteligência artificial, o Claude se destaca\nentre outros modelos de linguagem. Este ebook oferece uma análise\ncomparativa detalhada do Claude com seus principais concorrentes, como\nChatGPT, Gemini e Llama. Você aprenderá sobre os pontos fortes e fracos\nde cada modelo, suas arquiteturas, capacidades e as áreas onde cada um\nbrilha. Com uma avaliação imparcial e insights sobre o futuro da IA\nconversacional, este guia é essencial para quem deseja tomar decisões\ninformadas sobre qual modelo de linguagem utilizar em seus projetos e\nentender as nuances que diferenciam os gigantes da inteligência\nartificial.',
        'about_replace': 'No campo de batalha da inteligência artificial, o **Claude** emerge como um dos principais contendores. Este ebook é a sua arena para a **batalha dos gigantes da IA**, oferecendo uma análise comparativa detalhada do Claude com seus principais rivais: ChatGPT, Gemini, Llama e outros. Descubra os pontos fortes e fracos de cada modelo, suas arquiteturas, capacidades e as áreas onde cada um brilha. Com uma avaliação imparcial e insights sobre o futuro da IA conversacional, este guia é essencial para qualquer pessoa que deseja **tomar decisões informadas** sobre qual modelo de linguagem utilizar em seus projetos. Prepare-se para entender as nuances que diferenciam os líderes da revolução conversacional e **escolher a melhor IA para você**.'
    },
    '21_Claude_na_Pratica.md': {
        'title_find': '**Claude na Prática**',
        'title_replace': '**Claude na Prática: Desbloqueie o Potencial Máximo da IA Conversacional - Guia Essencial para Uso Diário**',
        'subtitle_find': '*Exemplos e Casos de Uso Reais para Aplicar o Claude em Seu Dia a Dia.*',
        'subtitle_replace': '*De Automação de Tarefas a Criação de Conteúdo: Aprenda a Utilizar o Claude para Otimizar Sua Produtividade e Criatividade.*',
        'about_find': 'Entender a teoria é importante, mas aplicar o Claude na prática é o que\nrealmente transforma. Este ebook é um guia prático repleto de exemplos e\ncasos de uso reais para você integrar o Claude em seu dia a dia. Você\naprenderá a utilizar o Claude para automação de tarefas, criação de\nconteúdo, suporte ao cliente, pesquisa e muito mais. Com tutoriais\npasso a passo e dicas de otimização, este guia é ideal para quem deseja\ntirar o máximo proveito do Claude e impulsionar sua produtividade e\ncriatividade. Prepare-se para transformar suas interações com a IA em\nresultados concretos.',
        'about_replace': 'Você está pronto para ir além da teoria e realmente **transformar seu dia a dia com a IA**? Este ebook é o seu guia essencial para o **Claude na Prática**, repleto de exemplos e casos de uso reais para você desbloquear o potencial máximo da IA conversacional. Aprenda a utilizar o Claude para automação de tarefas, criação de conteúdo, suporte ao cliente, pesquisa e muito mais. Com tutoriais passo a passo e dicas de otimização, este guia é ideal para qualquer pessoa que deseja **impulsionar sua produtividade e criatividade** e transformar suas interações com a IA em resultados concretos. Prepare-se para dominar o Claude e **revolucionar a forma como você trabalha e cria**.'
    },
    '22_Claude_para_Negocios.md': {
        'title_find': '**Claude para Negócios**',
        'title_replace': '**Claude para Negócios: A IA que Impulsiona o Crescimento e a Inovação - Estratégias Essenciais para Empresas**',
        'subtitle_find': '*Estratégias e Aplicações do Claude para Transformar Empresas e Impulsionar o Crescimento.*',
        'subtitle_replace': '*De Atendimento ao Cliente a Análise de Dados: Um Guia Completo para Integrar o Claude em Sua Operação Empresarial.*',
        'about_find': 'A inteligência artificial está redefinindo o cenário empresarial, e o\nClaude surge como uma ferramenta poderosa para impulsionar o crescimento\ne a inovação. Este ebook explora as estratégias e aplicações do Claude\npara transformar empresas de todos os portes. Você aprenderá como\nintegrar o Claude em atendimento ao cliente, marketing, vendas, análise\nde dados e desenvolvimento de produtos. Com casos de uso reais e dicas\nde implementação, este guia é essencial para empreendedores e gestores\nque desejam aproveitar o potencial da IA para otimizar operações,\nmelhorar a tomada de decisões e conquistar vantagem competitiva no\nmercado.',
        'about_replace': 'Sua empresa está pronta para a **revolução da inteligência artificial**? Este ebook é o seu guia essencial para o **Claude para Negócios**, a IA que impulsiona o crescimento e a inovação. Explore estratégias e aplicações do Claude para transformar sua operação empresarial, desde o atendimento ao cliente e marketing até vendas, análise de dados e desenvolvimento de produtos. Com casos de uso reais e dicas de implementação, este guia é indispensável para empreendedores e gestores que desejam **aproveitar o potencial da IA** para otimizar operações, melhorar a tomada de decisões e conquistar vantagem competitiva no mercado. Prepare-se para integrar o Claude em sua empresa e **impulsionar o crescimento e a inovação** como nunca antes.'
    },
    '23_Diferenciais_Tecnicos_do_Claude.md': {
        'title_find': '**Diferenciais Técnicos do Claude**',
        'title_replace': '**Claude: Diferenciais Técnicos que o Tornam Único - Uma Análise Profunda da Arquitetura e Inovação**',
        'subtitle_find': '*Uma Análise Aprofundada das Inovações e Vantagens Técnicas que Distinguem o Claude.*',
        'subtitle_replace': '*De IA Constitucional a Segurança Avançada: Descubra os Segredos por Trás do Modelo de Linguagem Mais Ético e Poderoso.*',
        'about_find': 'O Claude se destaca no cenário da inteligência artificial por seus\ndiferenciais técnicos e sua abordagem inovadora. Este ebook oferece uma\nanálise aprofundada das inovações e vantagens técnicas que distinguem o\nClaude de outros modelos de linguagem. Você aprenderá sobre a arquitetura\nque o torna tão eficiente, a filosofia de \"IA Constitucional\" que garante\nsua segurança e ética, e os algoritmos que o capacitam a ter conversas\nmais naturais e úteis. Com detalhes técnicos e insights sobre o futuro\nda IA, este guia é essencial para desenvolvedores, pesquisadores e\nentusiastas que desejam compreender a fundo o Claude e seu impacto na\nevolução da inteligência artificial.',
        'about_replace': 'Você quer ir além da superfície e realmente **entender o que torna o Claude único**? Este ebook é a sua porta de entrada para uma **análise profunda dos diferenciais técnicos do Claude**, revelando a arquitetura e as inovações que o distinguem no cenário da inteligência artificial. Explore a filosofia de "IA Constitucional" que garante sua segurança e ética, os algoritmos que o capacitam a ter conversas mais naturais e úteis, e as vantagens técnicas que o posicionam como um dos modelos de linguagem mais poderosos. Com detalhes técnicos e insights sobre o futuro da IA, este guia é essencial para desenvolvedores, pesquisadores e entusiastas que desejam **compreender a fundo o Claude** e seu impacto na evolução da inteligência artificial. Prepare-se para desvendar os segredos por trás do assistente de IA mais ético e poderoso.'
    },
    '24_Skills_Avancadas_com_Claude.md': {
        'title_find': '**Skills Avançadas com Claude**',
        'title_replace': '**Claude: Skills Avançadas - Domine a Criação de Soluções Inteligentes e Personalizadas com IA**',
        'subtitle_find': '*Explore o Potencial Máximo do Claude para Desenvolver Habilidades Personalizadas e Automações Complexas.*',
        'subtitle_replace': '*De Integrações com APIs a Agentes Autônomos: Um Guia Completo para Levar Suas Habilidades com Claude ao Próximo Nível.*',
        'about_find': 'O Claude não é apenas um assistente conversacional; ele é uma plataforma\npoderosa para desenvolver \"Skills\" personalizadas e automações\ncomplexas. Este ebook explora o potencial máximo do Claude para criar\nhabilidades avançadas, desde integrações com APIs externas até o\ndesenvolvimento de agentes autônomos. Você aprenderá sobre as melhores\npráticas de engenharia de prompt para Skills, como lidar com dados\ncomplexos, e como otimizar o desempenho de suas criações. Com exemplos\npráticos e dicas de especialistas, este guia é essencial para\ndesenvolvedores e entusiastas que desejam levar suas habilidades com\nClaude ao próximo nível e construir soluções inteligentes e\npersonalizadas.',
        'about_replace': 'Você está pronto para ir além do básico e **criar soluções inteligentes e personalizadas** que realmente fazem a diferença? Este ebook é o seu guia para as **Skills Avançadas com Claude**, explorando o potencial máximo da IA para desenvolver habilidades personalizadas e automações complexas. Aprenda sobre as melhores práticas de engenharia de prompt para Skills, como lidar com dados complexos e como otimizar o desempenho de suas criações. De integrações com APIs externas a agentes autônomos, este guia é essencial para desenvolvedores e entusiastas que desejam **levar suas habilidades com Claude ao próximo nível** e construir soluções que transformam. Prepare-se para dominar a criação de Skills avançadas e **desbloquear um novo patamar de inovação com a IA**.'
    },
    '25_Potencial_e_Futuro_do_Claude.md': {
        'title_find': '**Potencial e Futuro do Claude**',
        'title_replace': '**Claude: Potencial e Futuro - Desvendando as Próximas Fronteiras da Inteligência Artificial Conversacional**',
        'subtitle_find': '*Uma Visão Abrangente das Capacidades Emergentes e das Perspectivas para o Desenvolvimento do Claude.*',
        'subtitle_replace': '*De Interações Multimodais a Aplicações Inovadoras: Um Guia Essencial para Antecipar as Próximas Revoluções do Claude.*',
        'about_find': 'O Claude está em constante evolução, e seu potencial para transformar a\ninteração humana com a IA é imenso. Este ebook oferece uma visão\nabrangente das capacidades emergentes e das perspectivas para o\ndesenvolvimento do Claude. Você aprenderá sobre as próximas fronteiras da\nIA conversacional, como interações multimodais, personalização avançada\ne aplicações inovadoras em diversos setores. Com insights de\npesquisadores e projeções para o futuro, este guia é essencial para quem\ndeseja antecipar as próximas revoluções do Claude e se preparar para um\nmundo onde a inteligência artificial será ainda mais integrada e\npoderosa.',
        'about_replace': 'Você está pronto para vislumbrar as **próximas fronteiras da inteligência artificial conversacional**? Este ebook é o seu guia essencial para desvendar o **potencial e o futuro do Claude**, um modelo que está redefinindo a interação humana com a IA. Explore as capacidades emergentes, como interações multimodais e personalização avançada, e as aplicações inovadoras que transformarão diversos setores. Com insights de pesquisadores e projeções para o futuro, este guia é indispensável para qualquer pessoa que deseja **antecipar as próximas revoluções do Claude** e se preparar para um mundo onde a inteligência artificial será ainda mais integrada e poderosa. Prepare-se para uma visão que o capacitará a estar na vanguarda da inovação com a IA.'
    }
}

for filename in os.listdir(input_dir):
    if filename.endswith('.md'):
        filepath = os.path.join(input_dir, filename)
        revise_ebook(filepath, revisions)

print("Revisão automatizada concluída.")
